package vista;

import javax.swing.JButton;
import javax.swing.JOptionPane;
import funciones.DBManager;
import funciones.ReportService;
import java.io.File;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import modelo.Analisis;

public class EmpleadosVentana extends javax.swing.JFrame {

    public EmpleadosVentana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        TitleWelcome = new javax.swing.JLabel();
        AnalisisBtn = new javax.swing.JButton();
        Pacientesbtn = new javax.swing.JButton();
        DocumentosBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pacienteTextField = new javax.swing.JTextField();
        medicoTextField = new javax.swing.JTextField();
        fechaTextField = new javax.swing.JTextField();
        consultarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 500));

        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TitleWelcome.setText("Bienvenido, Empleado");

        AnalisisBtn.setText("Analisis");
        AnalisisBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnalisisBtnActionPerformed(evt);
            }
        });

        Pacientesbtn.setText("Pacientes");
        Pacientesbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PacientesbtnActionPerformed(evt);
            }
        });

        DocumentosBtn.setText("Documentos");
        DocumentosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DocumentosBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("ID Paciente:");

        jLabel2.setText("ID Médico:");

        jLabel3.setText("Fecha:");

        consultarButton.setText("Consultar");
        consultarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(247, 247, 247))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(TitleWelcome))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(AnalisisBtn)
                        .addGap(25, 25, 25)
                        .addComponent(Pacientesbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DocumentosBtn)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(TitleWelcome)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AnalisisBtn)
                    .addComponent(Pacientesbtn)
                    .addComponent(DocumentosBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AnalisisBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnalisisBtnActionPerformed
        int opcion = JOptionPane.showOptionDialog(this,
                "¿Qué deseas realizar?",
                "Seleccionar Opción",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                new String[]{"Consultar", "Registrar"},
                "Consultar");
        if (opcion == 0) {
            ConsultaAnalisisVentana consultaAnalisisVentana = new ConsultaAnalisisVentana();
            consultaAnalisisVentana.setVisible(true);
        } else if (opcion == 1) {
            RegistroAnalisisVentana registroAnalisisVentana = new RegistroAnalisisVentana();
            registroAnalisisVentana.setVisible(true);
        } 
    }//GEN-LAST:event_AnalisisBtnActionPerformed

    private void PacientesbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PacientesbtnActionPerformed
        int opcion =JOptionPane.showOptionDialog(this,
                "que deseas realizar?",
                "Seleccionar Opcion",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                new String[]{"consultar","registrar" } ,"consultar");
                if (opcion == 0){
                PacienteVentana PacienteVentana = new PacienteVentana ();
                PacienteVentana.setVisible(true);
                }else if (opcion ==1){
                PacienteVentana pacienteVentana = new PacienteVentana ();
                pacienteVentana.setVisible(true);
                }
    }//GEN-LAST:event_PacientesbtnActionPerformed

    private void DocumentosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DocumentosBtnActionPerformed
        String idPacienteStr = JOptionPane.showInputDialog(this, "Ingrese su número de ID de paciente:");
        try {
            if (idPacienteStr != null && !idPacienteStr.isEmpty()) {
                int idPaciente = Integer.parseInt(idPacienteStr);
                List<Analisis> analisisPaciente = DBManager.obtenerAnalisisPaciente(idPaciente);

                if (!analisisPaciente.isEmpty()) {
                    JFileChooser chooser = new JFileChooser();
                    chooser.setDialogTitle("Seleccionar Carpeta de Salida");
                    chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

                    int result = chooser.showOpenDialog(this);
                    if (result == JFileChooser.APPROVE_OPTION) {
                        File selectedFolder = chooser.getSelectedFile();
                        String carpetaSalida = selectedFolder.getAbsolutePath();
                        ReportService.generarInformeAnalisis(analisisPaciente, carpetaSalida);
                        JOptionPane.showMessageDialog(this, "Informe de análisis generado correctamente.", "Informe Generado", JOptionPane.INFORMATION_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "El número de ID de paciente ingresado no tiene análisis asociados.", "No Hay Análisis", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Ingrese un número de ID de paciente válido.", "Campo Vacío", JOptionPane.WARNING_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese un número válido para el ID de paciente.", "Error de Entrada", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_DocumentosBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmpleadosVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmpleadosVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmpleadosVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmpleadosVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmpleadosVentana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnalisisBtn;
    private javax.swing.JButton DocumentosBtn;
    private javax.swing.JPanel Fondo;
    private javax.swing.JButton Pacientesbtn;
    private javax.swing.JLabel TitleWelcome;
    private javax.swing.JButton consultarButton;
    private javax.swing.JTextField fechaTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField medicoTextField;
    private javax.swing.JTextField pacienteTextField;
    // End of variables declaration//GEN-END:variables
}
