package vista;

import javax.swing.JOptionPane;
import funciones.ControlLogin;
import modelo.RolUsuario;

public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        TxtTitle = new javax.swing.JLabel();
        LoginPanel = new javax.swing.JPanel();
        LoginBtn = new javax.swing.JButton();
        UserLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        UserInput = new javax.swing.JTextField();
        PassInput = new javax.swing.JPasswordField();
        Title = new javax.swing.JLabel();
        Text = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 255));

        Fondo.setBackground(new java.awt.Color(102, 102, 255));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TxtTitle.setFont(new java.awt.Font("Sitka Heading", 0, 36)); // NOI18N
        TxtTitle.setText("Hospital General");
        Fondo.add(TxtTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        LoginPanel.setBackground(new java.awt.Color(204, 204, 204));
        LoginPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        LoginPanel.setAutoscrolls(true);
        LoginPanel.setPreferredSize(new java.awt.Dimension(400, 200));

        LoginBtn.setBackground(new java.awt.Color(255, 255, 102));
        LoginBtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        LoginBtn.setText("Ingresar");
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });

        UserLabel.setText("Usuario:");

        jLabel2.setText("Password:");

        UserInput.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N

        javax.swing.GroupLayout LoginPanelLayout = new javax.swing.GroupLayout(LoginPanel);
        LoginPanel.setLayout(LoginPanelLayout);
        LoginPanelLayout.setHorizontalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginPanelLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(UserLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(UserInput, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(LoginBtn))
                    .addComponent(PassInput))
                .addGap(84, 84, 84))
        );
        LoginPanelLayout.setVerticalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginPanelLayout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserLabel)
                    .addComponent(UserInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(PassInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(LoginBtn)
                .addGap(19, 19, 19))
        );

        Title.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        Title.setText("Login");

        Text.setText("Ingrese sus Credenciales");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(LoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(Text))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(Title)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
        // Recolectar datos ingresados por el usuario
        String nombreUsuario = UserInput.getText();
        String password = new String(PassInput.getPassword()); // Convierte los caracteres a String

        // Verificar las credenciales del usuario y obtener su rol
        RolUsuario rolUsuario = ControlLogin.verificarCredenciales(nombreUsuario, password);

        if (rolUsuario != null) {
            // Credenciales correctas, determinar la ventana correspondiente según el rol
            switch (rolUsuario) {
                case paciente:
                    // Abrir ventana para pacientes
                    PacienteVentana pacienteVentana = new PacienteVentana(); 
                    pacienteVentana.setVisible(true);
                    break;
                case enfermero:
                    // Abrir ventana para enfermeros
                    EmpleadosVentana enfermeroVentana = new EmpleadosVentana(); 
                    enfermeroVentana.setVisible(true);
                    break;
                case doctor:
                    // Abrir ventana para doctores
                    EmpleadosVentana doctorVentana = new EmpleadosVentana(); 
                    doctorVentana.setVisible(true);
                    break;
                default:
                    // Rol no reconocido, mostrar mensaje de error
                    JOptionPane.showMessageDialog(this, "Rol de usuario no reconocido", "Error de inicio de sesión", JOptionPane.ERROR_MESSAGE);
                    break;
            }

            // Cerrar la ventana actual (ventana de inicio de sesión)
            this.dispose();
        } else {
            // Credenciales incorrectas, mostrar mensaje de error
            JOptionPane.showMessageDialog(this, "Nombre de usuario o contraseña incorrectos", "Error de inicio de sesión", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_LoginBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fondo;
    private javax.swing.JButton LoginBtn;
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JPasswordField PassInput;
    private javax.swing.JLabel Text;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel TxtTitle;
    private javax.swing.JTextField UserInput;
    private javax.swing.JLabel UserLabel;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
