package vista;

import funciones.RegistroAnalisis;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import modelo.Analisis;
import java.util.Date;
import javax.swing.DefaultListModel;

public class RegistroAnalisisVentana extends javax.swing.JFrame {

    private DefaultListModel<String> idPacienteListModel;
    
    public RegistroAnalisisVentana() {
        initComponents();
        idPacienteListModel = new DefaultListModel<>();
        obtenerIDsDePacientes();
    }
    
    private void obtenerIDsDePacientes(){
        idPacienteListModel.clear();
        java.util.List<Integer> idPacientes = funciones.RegistroAnalisis.PacienteDAO.obtenerIDsPacientes();
        for (Integer id : idPacientes){
            idPacienteListModel.addElement(String.valueOf(id));
        }
        idpacienteList.setModel(idPacienteListModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idPacienteTextField = new javax.swing.JTextField();
        tipoAnalisisTextField = new javax.swing.JTextField();
        fechaRealizacionDatePicker = new javax.swing.JTextField();
        medicoSolicitanteTextField = new javax.swing.JTextField();
        enfermeroRealizadorTextField = new javax.swing.JTextField();
        resultadoTextField = new javax.swing.JTextField();
        RegistrarBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        idpacienteList = new javax.swing.JList<>();
        Title = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        idPacienteTextField.setMinimumSize(new java.awt.Dimension(150, 22));

        tipoAnalisisTextField.setMaximumSize(new java.awt.Dimension(150, 25));
        tipoAnalisisTextField.setMinimumSize(new java.awt.Dimension(150, 25));

        fechaRealizacionDatePicker.setMaximumSize(new java.awt.Dimension(150, 25));
        fechaRealizacionDatePicker.setMinimumSize(new java.awt.Dimension(150, 25));

        medicoSolicitanteTextField.setMaximumSize(new java.awt.Dimension(150, 25));
        medicoSolicitanteTextField.setMinimumSize(new java.awt.Dimension(150, 25));

        enfermeroRealizadorTextField.setMaximumSize(new java.awt.Dimension(150, 25));
        enfermeroRealizadorTextField.setMinimumSize(new java.awt.Dimension(150, 25));

        resultadoTextField.setMaximumSize(new java.awt.Dimension(150, 25));
        resultadoTextField.setMinimumSize(new java.awt.Dimension(150, 25));

        RegistrarBtn.setText("Registrar");
        RegistrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarBtnActionPerformed(evt);
            }
        });

        idpacienteList.setModel(new javax.swing.DefaultListModel<>());
        jScrollPane1.setViewportView(idpacienteList);

        Title.setText("Registro Analisis");

        jLabel1.setText("Id Del Paciente");

        jLabel2.setText("Tipo de Analisis:");

        jLabel3.setText("Fecha (yyyy-mm-dd)");

        jLabel4.setText("Medico que la realizo (ID)");

        jLabel5.setText("Enfermero que la realizo (ID)");

        jLabel6.setText("Resultados (Observaciones)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idPacienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Title)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tipoAnalisisTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fechaRealizacionDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(medicoSolicitanteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(enfermeroRealizadorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(180, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(resultadoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(297, 297, 297)
                .addComponent(RegistrarBtn)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(Title)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idPacienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(37, 37, 37)
                            .addComponent(jLabel5))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(tipoAnalisisTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(fechaRealizacionDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(medicoSolicitanteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4))
                            .addGap(3, 3, 3)
                            .addComponent(enfermeroRealizadorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resultadoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(27, 27, 27)
                .addComponent(RegistrarBtn)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarBtnActionPerformed
        String idPacienteSeleccionado = idpacienteList.getSelectedValue();
        if(idPacienteSeleccionado == null){
            JOptionPane.showMessageDialog(this, "Seleccione un Paciente", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int idPaciente = Integer.parseInt(idPacienteSeleccionado);
        String tipoAnalisis = tipoAnalisisTextField.getText();
        String fechaRealizacionText = fechaRealizacionDatePicker.getText();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        Date fechaRealDate = null;
        try{
            fechaRealDate = dateFormat.parse(fechaRealizacionText);
        } catch (ParseException e){
            e.printStackTrace();
        }
        if (fechaRealDate != null){
            java.sql.Date fechaRealiDate = new java.sql.Date(fechaRealDate.getTime());
            int medicoSolicitante = Integer.parseInt(medicoSolicitanteTextField.getText());
            int enfermeroRealizador = Integer.parseInt(enfermeroRealizadorTextField.getText());
            String resultado = resultadoTextField.getText();
            Analisis nuevoAnalisis = new Analisis(idPaciente, tipoAnalisis, fechaRealiDate, medicoSolicitante, enfermeroRealizador, resultado);
            boolean exito = RegistroAnalisis.registrarAnalisis(nuevoAnalisis);
            if (exito) {
                JOptionPane.showMessageDialog(this, "El análisis se ha registrado correctamente.", "Registro Exitoso", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo registrar el análisis. Por favor, inténtelo de nuevo.", "Error de Registro", JOptionPane.ERROR_MESSAGE);
            } 
        } else{
            JOptionPane.showMessageDialog(this, "La fecha ingresada no es válida. Por favor, ingrese una fecha en el formato yyyy-MM-dd.", "Error de Formato de Fecha", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_RegistrarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroAnalisisVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroAnalisisVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroAnalisisVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroAnalisisVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroAnalisisVentana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RegistrarBtn;
    private javax.swing.JLabel Title;
    private javax.swing.JTextField enfermeroRealizadorTextField;
    private javax.swing.JTextField fechaRealizacionDatePicker;
    private javax.swing.JTextField idPacienteTextField;
    private javax.swing.JList<String> idpacienteList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField medicoSolicitanteTextField;
    private javax.swing.JTextField resultadoTextField;
    private javax.swing.JTextField tipoAnalisisTextField;
    // End of variables declaration//GEN-END:variables
}
